language: cpp
compiler:
    - gcc
    - clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
       packages:
            - g++-4.8
            - clang-3.5
            - valgrind
before_script:
    - echo $(clang++ --version)
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5"; fi
script:
    - cd tests && cmake . && make
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --tool=memcheck --leak-check=full --error-exitcode=1 ./test_all; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./test_all; fi
branches:
    only:
        - master
        - develop
os:
    - linux
    - osx
